sudo: required

language: python

services:
  - docker

before_install:
  - docker build -t mycroft-docker .
  - docker run -itd -p 127.0.0.1:8181:8181 --name mycroft-docker mycroft-docker /bin/bash /mycroft/ai/mycroft.sh start -d"


script:
  - docker ps | grep -q mycroft-docker
